steps:

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 2.1.x'
  inputs:
    packageType: sdk
    version: 2.1.x
    installationPath: $(Agent.ToolsDirectory)
    includePreviewVersions: true

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 5.8

# Restore

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore

    projects: '**/DroneStatus/dotnet/**/*.csproj'

# Build
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/DroneStatus/dotnet/**/*.csproj'

    arguments: '--configuration $(BuildConfiguration)'

# Run tests
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test

    projects: '**/DroneStatus/dotnet/**.Tests/*.csproj'

    publishTestResults: true

    arguments: '--configuration $(BuildConfiguration)'

  enabled: true

# Publish

   
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish

    publishWebProjects: false

    projects: '**/DroneStatus/dotnet/DroneStatusFunctionApp/*.csproj'

    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

    zipAfterPublish: True

# Publish Artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
